apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: secoda
spec:
  title: Secoda
  icon: "https://cdn.prod.website-files.com/648302318a1143aaf5e78dfa/662e7e94b56b979257642b08_secoda.png"
  ports:
    - serviceName: secoda-frontend
      servicePort: 80
      localPort: 8080
      applicationUrl: "http://localhost:8080"
  statusInformers:
    - deployment/secoda-api
    - deployment/secoda-frontend