# Default values for secoda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

services:
  api:
    image:
      registry: ""
      name: "on-premise-api"
      pullPolicy: IfNotPresent
      tag: ""
    secret: ""  # Will be set from UI config
    publicKey: ""  # Will be set from UI config
    privateKey: ""  # Will be set from UI config
    env: []
    ports:
      - containerPort: 5007
    resources:
      requests:
        memory: 16384Mi
        cpu: 2048m
        ephemeral-storage: 9Gi
      limits:
        memory: 16384Mi
        cpu: 2048m
        ephemeral-storage: 9Gi
    livenessProbe:
      tcpSocket:
        port: 5007
      timeoutSeconds: 10
    readinessProbe:
      tcpSocket:
        port: 5007
      timeoutSeconds: 10
    startupProbe:
      tcpSocket:
        port: 5007
      failureThreshold: 30
      periodSeconds: 30
    securityContext: {}

  frontend:
    image:
      registry: ""
      name: "on-premise-frontend"
      pullPolicy: IfNotPresent
      tag: ""
    args: []
    env: []
    ports:
      - name: https
        containerPort: 443
      - name: http
        containerPort: 80
    resources:
      requests:
        memory: 1024Mi
        cpu: 512m
        ephemeral-storage: 4Gi
      limits:
        memory: 1024Mi
        cpu: 512m
        ephemeral-storage: 4Gi
    livenessProbe:
      tcpSocket:
        port: 5006
      initialDelaySeconds: 30
      timeoutSeconds: 5
    readinessProbe:
      tcpSocket:
        port: 5006
      initialDelaySeconds: 30
      timeoutSeconds: 5
    securityContext: {}

global:
  image:
    registry: "secoda"
    pullPolicy: Always
    tag: "latest"
  env: []
  resources: {}
  securityContext:
    {}
    # allowPrivilegeEscalation: false

persistence:
  enabled: false

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

service:
  type: NodePort

nodeSelector: {}
tolerations: []
affinity: {}
dnsConfig: {}
annotations: {}

## Redis Configuration
## ref: https://github.com/bitnami/charts/tree/main/bitnami/redis
redis:
  enabled: true
  architecture: standalone
  image:
    tag: "6.2.7-debian-11-r3"  # Redis 6.2.x
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 2Gi
        cpu: 1
      limits:
        memory: 2Gi
        cpu: 1
    replicaCount: 1  # Minimum 1 replica

## PostgreSQL Configuration
## ref: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  enabled: true
  image:
    tag: "14.10.0-debian-11-r14"  # PostgreSQL 14.x
  auth:
    username: keycloak
    password: keycloak  # This should be configured through UI
    database: secoda
  primary:
    persistence:
      enabled: true
      size: 100Gi
    resources:
      requests:
        memory: 8Gi
        cpu: 2
      limits:
        memory: 8Gi
        cpu: 2

## OpenSearch Configuration
## ref: https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch
opensearch:
  enabled: false
  image:
    tag: "2.9.0"  # OpenSearch 2.x
  singleNode: false  # Allow for cluster mode
  config:
    opensearch.yml: |
      cluster.name: opensearch-cluster
      # Enable security features
      plugins.security.disabled: false
      # Configure master user
      plugins.security.authc:
        basic_internal_auth_domain:
          description: "Basic auth for internal users"
          http_enabled: true
          transport_enabled: true
          order: 0
          http_authenticator:
            type: basic
            challenge: true
          authentication_backend:
            type: internal
  auth:
    adminUser: admin
    adminPassword: admin  # This should be configured through UI
  persistence:
    enabled: true
    size: 20Gi
  resources:
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 1
  javaOpts: "-Xmx2g -Xms2g"  # Set to half of memory for optimal performance

## OpenSearch Dashboards Configuration
## ref: https://github.com/opensearch-project/helm-charts/tree/main/charts/opensearch-dashboards
opensearchDashboards:
  enabled: false
  opensearchHosts: "http://{{ .Release.Name }}-opensearch:9200"
  config:
    opensearch_dashboards.yml: |
      server.name: opensearch-dashboards
      server.host: "0.0.0.0"
      # Disable security features for simplicity
      opensearch_security.disabled: true
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
    limits:
      memory: 512Mi
      cpu: 300m
