apiVersion: v1
kind: Service
metadata:
  name: {{ include "secoda.fullname" . }}-frontend
  labels:
    {{- include "secoda.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    {{- include "secoda.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
